Repository codestates-seb/seb40_main_027, pull requests merged in 2022-11, with the labels that each got.

#13 Feat/#8/configure exception
  .gitignore
  server/out/production/classes/com/yes27/ServerApplication.class
  server/out/production/classes/com/yes27/advice/GlobalExceptionAdvice.class
  server/out/production/classes/com/yes27/exception/BusinessLogicException.class
  server/out/production/classes/com/yes27/exception/ExceptionCode.class
  server/out/production/classes/com/yes27/response/ErrorResponse$ConstraintViolationError.class
  server/out/production/classes/com/yes27/response/ErrorResponse$FieldError.class
  server/out/production/classes/com/yes27/response/ErrorResponse.class
  server/out/production/classes/com/yes27/response/MultiResponseDto.class
  server/out/production/classes/com/yes27/response/PageInfo.class
  server/out/production/classes/com/yes27/response/SingleResponseDto.class
  server/out/production/classes/com/yes27/study/entity/Study.class
  server/out/production/resources/application.yml
  server/src/main/java/com/yes27/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/yes27/exception/BusinessLogicException.java
  server/src/main/java/com/yes27/exception/ExceptionCode.java
  server/src/main/java/com/yes27/response/ErrorResponse.java
  server/src/main/java/com/yes27/response/MultiResponseDto.java
  server/src/main/java/com/yes27/response/PageInfo.java
  server/src/main/java/com/yes27/response/SingleResponseDto.java
Labels: be

#16 feat: configure basic spring security
  server/src/main/java/com/yes27/config/SecurityConfig.java
Labels: be

#29 feat: member 및 study 구성 기본 Controler Service Repository 구성
  server/build.gradle
  server/out/production/classes/com/yes27/config/SecurityConfig.class
  server/out/production/classes/com/yes27/member/controller/MemberController.class
  server/out/production/classes/com/yes27/member/dto/MemberDto$Patch.class
  server/out/production/classes/com/yes27/member/dto/MemberDto$Post.class
  server/out/production/classes/com/yes27/member/dto/MemberDto$Response.class
  server/out/production/classes/com/yes27/member/dto/MemberDto.class
  server/out/production/classes/com/yes27/member/entity/Member.class
  server/out/production/classes/com/yes27/member/mapper/MemberMapper.class
  server/out/production/classes/com/yes27/member/mapper/MemberMapperImpl.class
  server/out/production/classes/com/yes27/member/repository/MemberRepository.class
  server/out/production/classes/com/yes27/member/service/MemberService.class
  server/out/production/classes/com/yes27/study/controller/StudyController.class
  server/out/production/classes/com/yes27/study/dto/StudyDto$Patch.class
  server/out/production/classes/com/yes27/study/dto/StudyDto$Post.class
  server/out/production/classes/com/yes27/study/dto/StudyDto$Response.class
  server/out/production/classes/com/yes27/study/dto/StudyDto.class
  server/out/production/classes/com/yes27/study/mapper/StudyMapper.class
  server/out/production/classes/com/yes27/study/mapper/StudyMapperImpl.class
  server/out/production/classes/com/yes27/study/repository/StudyRepository.class
  server/out/production/classes/com/yes27/study/service/StudyService.class
  server/src/main/generated/com/yes27/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/yes27/study/mapper/StudyMapperImpl.java
  server/src/main/java/com/yes27/member/controller/MemberController.java
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/entity/Member.java
  server/src/main/java/com/yes27/member/mapper/MemberMapper.java
  server/src/main/java/com/yes27/member/repository/MemberRepository.java
  server/src/main/java/com/yes27/member/service/MemberService.java
  server/src/main/java/com/yes27/study/controller/StudyController.java
  server/src/main/java/com/yes27/study/dto/StudyDto.java
  server/src/main/java/com/yes27/study/mapper/StudyMapper.java
  server/src/main/java/com/yes27/study/repository/StudyRepository.java
  server/src/main/java/com/yes27/study/service/StudyService.java
Labels: be

#19 client-sanghyun: Feat/#11 footer
  client/src/components/Footer/Footer.tsx
Labels: fe

#17 client-yoonkyoung : Feat/#7 header,logo
  client/src/App.tsx
  client/src/components/Header/MainHeader.tsx
  client/src/components/Header/Nickname.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/image/icon.png
  client/src/image/logo.png
  client/src/image/mainbanner.png
  client/src/image/mainmobile.png
  client/src/image/review.png
  client/src/image/reviewmobile.png
  client/src/image/scheduledetails.png
  client/src/image/scheduledetailsmobile.png
Labels: fe

#22 client-sanghyun: Feat/#20 search bar
  client/package-lock.json
  client/package.json
  client/src/components/SearchBar/index.tsx
Labels: fe

#35 client-jongwon: 공통 버튼 작성
  client/src/components/Button/BackgroundButton.tsx
  client/src/components/Button/BorderButton.tsx
  client/src/components/Button/FilterButton.tsx
  client/src/components/Button/LoginButton.tsx
  client/src/components/Button/OtherButton.tsx
  client/src/components/Button/RegisterButton.tsx
  client/src/components/Button/TagButton.tsx
  client/src/components/Button/WriteButton.tsx
  client/src/components/Button/index.tsx
  client/src/styles/GlobalStyle.tsx
Labels: fe

#57 clinet-sanghyun: Feat/#18 banner
  client/.eslintrc.json
  client/src/assets/constant/COLOR.ts
  client/src/assets/image/boardimage.png
  client/src/assets/image/bootimage.png
  client/src/components/Banner/index.tsx
  client/src/pages/Main.tsx
  client/src/pages/index.js
  client/src/styles/GlobalStyle.tsx
Labels: fe

#79 Feat/#77 postscript tag
  server/src/main/java/com/yes27/postscript/dto/TagDto.java
  server/src/main/java/com/yes27/postscript/entity/Tag.java
  server/src/main/java/com/yes27/postscript/repository/PostscriptLikeRepository.java
  server/src/main/java/com/yes27/postscript/repository/TagRepository.java
  server/src/main/java/com/yes27/postscript/service/PostscriptLikeService.java
  server/src/main/java/com/yes27/postscript/service/TagService.java
Labels: be, BareMinimum

#72 client-sanghyun: Feat/##53 loginpage
  client/src/App.tsx
  client/src/components/Banner/index.style.tsx
  client/src/components/Banner/index.tsx
  client/src/components/Button/LoginButton.tsx
  client/src/components/Button/index.tsx
  client/src/pages/Login.tsx
Labels: fe

#51 client-yoonkyoung: mainpage view구현
  client/src/App.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/pages/Main.tsx
Labels: fe

#91 Feat#90 patch member
  server/src/main/java/com/yes27/member/controller/MemberController.java
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/entity/Member.java
  server/src/main/java/com/yes27/member/service/MemberService.java
  server/src/main/java/com/yes27/study/dto/StudyDto.java
Labels: be, BareMinimum

#92 fix : Postscript 게시판 태그기능 bug fix #77
  server/src/main/java/com/yes27/postscript/controller/PostscriptController.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptDto.java
  server/src/main/java/com/yes27/postscript/dto/TagDto.java
  server/src/main/java/com/yes27/postscript/entity/Postscript.java
  server/src/main/java/com/yes27/postscript/entity/Tag.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptMapper.java
  server/src/main/java/com/yes27/postscript/service/PostscriptService.java
Labels: be

#67 client-yoonkyoung: mypage구현
  client/src/App.tsx
  client/src/assets/constant/COLOR.ts
  client/src/atoms/index.js
  client/src/atoms/index.tsx
  client/src/components/Button/LoginButton.tsx
  client/src/components/Header/MainHeader.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/components/MyPageContent/MyPageList.tsx
  client/src/components/MyPageContent/MyPageSchedule.style.ts
  client/src/components/MyPageContent/MyPageSchedule.tsx
  client/src/components/SideBar/SideBar.style.ts
  client/src/components/SideBar/SideBar.tsx
  client/src/index.tsx
  client/src/pages/MyPage.style.ts
  client/src/pages/MyPage.tsx
  client/src/styles/GlobalStyle.tsx
Labels: fe

#100 Feat/#70 user insertion
  server/src/main/java/com/yes27/member/controller/MemberController.java
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/entity/Member.java
  server/src/main/java/com/yes27/member/mapper/MemberMapper.java
  server/src/main/java/com/yes27/study/controller/StudyController.java
  server/src/main/java/com/yes27/study/dto/StudyDto.java
  server/src/main/java/com/yes27/study/entity/Study.java
  server/src/main/java/com/yes27/study/mapper/StudyMapper.java
  server/src/main/java/com/yes27/study_comment/controller/StudyCommentController.java
  server/src/main/java/com/yes27/study_comment/dto/StudyCommentDto.java
  server/src/main/java/com/yes27/study_comment/entity/StudyComment.java
  server/src/main/java/com/yes27/study_comment/mapper/StudyCommentMapper.java
Labels: be, BareMinimum

#110 Feat/#104 jwt
  server/build.gradle
  server/src/main/java/com/yes27/auth/dto/LoginDto.java
  server/src/main/java/com/yes27/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/yes27/auth/handler/ErrorResponder/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/yes27/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/yes27/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/yes27/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/yes27/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/yes27/auth/jwt/JwtVerificationFilter.java
  server/src/main/java/com/yes27/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/yes27/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/yes27/auth/utils/ErrorResponder.java
  server/src/main/java/com/yes27/config/SecurityConfig.java
  server/src/main/java/com/yes27/member/controller/MemberController.java
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/entity/Member.java
  server/src/main/java/com/yes27/member/mapper/MemberMapper.java
  server/src/main/java/com/yes27/member/service/MemberService.java
  server/src/main/java/com/yes27/study/dto/StudyDto.java
  server/src/main/java/com/yes27/study_comment/controller/StudyCommentController.java
  server/src/main/java/com/yes27/validator/NotSpace.java
  server/src/main/java/com/yes27/validator/NotSpaceValidator.java
Labels: be, BareMinimum

#113 feat: Member ResponseEntity 수정
  server/src/main/java/com/yes27/member/controller/MemberController.java
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/mapper/MemberMapper.java
  server/src/main/java/com/yes27/member/service/MemberService.java
Labels: be, BareMinimum

#109 client-yoonkyoung: testpage페이지 구현
  client/package-lock.json
  client/src/App.tsx
  client/src/assets/image/flower1.png
  client/src/assets/image/pra1.png
  client/src/assets/image/result1.png
  client/src/atoms/index.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/components/TestForm/EndForm.style.ts
  client/src/components/TestForm/EndForm.tsx
  client/src/components/TestForm/StartForm.style.ts
  client/src/components/TestForm/StartForm.tsx
  client/src/components/TestForm/TypeForm.style.ts
  client/src/components/TestForm/TypeForm.tsx
  client/src/components/TestForm/WarningWindow.style.ts
  client/src/components/TestForm/WarningWindow.tsx
  client/src/pages/Test.style.ts
  client/src/pages/Test.tsx
Labels: fe, BareMinimum

#115 client-jongwon: 게시판 - view 작업
  client/src/App.tsx
  client/src/assets/constant/COLOR.ts
  client/src/components/Button/FilterButton.tsx
  client/src/components/Button/MoreButton.style.ts
  client/src/components/Button/MoreButton.tsx
  client/src/components/Button/TagButton.tsx
  client/src/components/Button/index.tsx
  client/src/components/Forum/ForumArticle.style.ts
  client/src/components/Forum/ForumArticle.tsx
  client/src/components/Forum/ForumArticles.style.ts
  client/src/components/Forum/ForumArticles.tsx
  client/src/components/Forum/ForumCard.style.ts
  client/src/components/Forum/ForumCard.tsx
  client/src/components/Forum/ForumCards.style.ts
  client/src/components/Forum/ForumCards.tsx
  client/src/components/Forum/ForumDetail.style.ts
  client/src/components/Forum/ForumDetail.tsx
  client/src/components/Forum/ForumSideBanners.style.ts
  client/src/components/Forum/ForumSideBanners.tsx
  client/src/components/Forum/ForumWrite.style.ts
  client/src/components/Forum/ForumWrite.tsx
  client/src/components/Forum/ForumWrittenInfo.style.ts
  client/src/components/Forum/ForumWrittenInfo.tsx
  client/src/components/Pagination/index.style.tsx
  client/src/components/Pagination/index.tsx
  client/src/pages/Forum.style.ts
  client/src/pages/Forum.tsx
  client/src/styles/GlobalStyle.tsx
Labels: fe, BareMinimum

#108 client-sanghyun: Feat/#73 signuppage
  client/src/App.tsx
  client/src/components/Banner/index.style.tsx
  client/src/components/Button/LoginButton.tsx
  client/src/components/Button/RegisterButton.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/SearchBar/ SearchBar.tsx
  client/src/components/SearchBar/index.tsx
  client/src/components/index.js
  client/src/pages/SignUp.style.tsx
  client/src/pages/SignUp.tsx
Labels: fe, BareMinimum

#149 Feat/#142 postscript jwt
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/entity/Member.java
  server/src/main/java/com/yes27/member/mapper/MemberMapper.java
  server/src/main/java/com/yes27/member/service/MemberService.java
  server/src/main/java/com/yes27/postscripcomment/controller/PostscriptCommentController.java
  server/src/main/java/com/yes27/postscripcomment/dto/PostscriptCommentDto.java
  server/src/main/java/com/yes27/postscripcomment/entity/PostscriptComment.java
  server/src/main/java/com/yes27/postscripcomment/mapper/PostscriptCommentMapper.java
  server/src/main/java/com/yes27/postscripcomment/service/PostscriptCommentService.java
  server/src/main/java/com/yes27/postscript/controller/PostscriptController.java
  server/src/main/java/com/yes27/postscript/controller/PostscriptVoteController.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptDto.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptVoteResponseDto.java
  server/src/main/java/com/yes27/postscript/entity/Postscript.java
  server/src/main/java/com/yes27/postscript/entity/PostscriptVote.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptMapper.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptVoteMapper.java
  server/src/main/java/com/yes27/postscript/repository/PostscriptVoteRepository.java
  server/src/main/java/com/yes27/postscript/service/PostscriptService.java
  server/src/main/java/com/yes27/postscript/service/PostscriptVoteService.java
Labels: be

#152 Feat/#150 jwt like view
  server/src/main/java/com/yes27/exception/ExceptionCode.java
  server/src/main/java/com/yes27/member/controller/MemberController.java
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/entity/Member.java
  server/src/main/java/com/yes27/member/mapper/MemberMapper.java
  server/src/main/java/com/yes27/study/controller/StudyController.java
  server/src/main/java/com/yes27/study/controller/StudyVoteController.java
  server/src/main/java/com/yes27/study/dto/StudyDto.java
  server/src/main/java/com/yes27/study/entity/Study.java
  server/src/main/java/com/yes27/study/entity/StudyView.java
  server/src/main/java/com/yes27/study/entity/StudyVote.java
  server/src/main/java/com/yes27/study/mapper/StudyMapper.java
  server/src/main/java/com/yes27/study/repository/StudyRepository.java
  server/src/main/java/com/yes27/study/repository/StudyViewRepository.java
  server/src/main/java/com/yes27/study/repository/StudyVoteRepository.java
  server/src/main/java/com/yes27/study/service/StudyService.java
  server/src/main/java/com/yes27/study/service/StudyViewService.java
  server/src/main/java/com/yes27/study/service/StudyVoteService.java
  server/src/main/java/com/yes27/study_comment/controller/StudyCommentController.java
  server/src/main/java/com/yes27/study_comment/dto/StudyCommentDto.java
  server/src/main/java/com/yes27/study_comment/entity/StudyComment.java
  server/src/main/java/com/yes27/study_comment/mapper/StudyCommentMapper.java
  server/src/main/java/com/yes27/study_comment/service/StudyCommentService.java
Labels: be, BareMinimum

#167 Fix/#166 postscript
  server/src/main/java/com/yes27/postscripcomment/controller/PostscriptCommentController.java
  server/src/main/java/com/yes27/postscripcomment/dto/PostscriptCommentDto.java
  server/src/main/java/com/yes27/postscripcomment/entity/PostscriptComment.java
  server/src/main/java/com/yes27/postscripcomment/mapper/PostscriptCommentMapper.java
  server/src/main/java/com/yes27/postscripcomment/repository/PostscriptCommentRepository.java
  server/src/main/java/com/yes27/postscripcomment/service/PostscriptCommentService.java
  server/src/main/java/com/yes27/postscript/controller/PostscriptController.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptDto.java
  server/src/main/java/com/yes27/postscript/entity/Postscript.java
  server/src/main/java/com/yes27/postscript/entity/Tag.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptMapper.java
  server/src/main/java/com/yes27/postscript/repository/PostscriptRepository.java
  server/src/main/java/com/yes27/postscript/service/PostscriptService.java
Labels: be, BareMinimum

#183 Feat/#182 mypage writing/userinfo
  server/src/main/java/com/yes27/member/controller/MemberController.java
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/member/mapper/MemberMapper.java
  server/src/main/java/com/yes27/mentoring/repository/MentorRepository.java
  server/src/main/java/com/yes27/mentoring/service/MentorService.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptDto.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptMapper.java
  server/src/main/java/com/yes27/postscript/repository/PostscriptRepository.java
  server/src/main/java/com/yes27/study/repository/StudyRepository.java
  server/src/main/java/com/yes27/study/service/StudyService.java
Labels: be, BareMinimum

#185 Feat/#184 study sort and study comment nickname
  server/src/main/java/com/yes27/study/dto/StudyDto.java
  server/src/main/java/com/yes27/study/mapper/StudyMapper.java
  server/src/main/java/com/yes27/study/service/StudyService.java
Labels: be, BareMinimum

#189 fix : Postscript Tag 데이터 타입변경 #187
  server/src/main/java/com/yes27/postscript/dto/PostscriptDto.java
  server/src/main/java/com/yes27/postscript/entity/Postscript.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptMapper.java
  server/src/main/java/com/yes27/postscript/repository/TagRepository.java
  server/src/main/java/com/yes27/postscript/service/PostscriptService.java
  server/src/main/java/com/yes27/postscript/service/TagService.java
Labels: be, BareMinimum

#156 client -yoonkyoung :my profile구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Button/Logout.style.ts
  client/src/components/Button/Logout.tsx
  client/src/components/Header/Nickname.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/components/Header/PageHeaderSide.tsx
  client/src/components/MyPageContent/MyPageList.tsx
  client/src/components/MyPageContent/MyPageLists.style.ts
  client/src/components/MyPageContent/MyPageLists.tsx
  client/src/components/MyPageContent/MyPageSchedule.style.ts
  client/src/components/MyPageContent/MyPageSchedule.tsx
  client/src/components/MyPageContent/MyPageTable.style.ts
  client/src/components/MyPageContent/MyPageTable.tsx
  client/src/components/MyPageContent/UserProfile.style.ts
  client/src/components/MyPageContent/UserProfile.tsx
  client/src/components/SideBar/SideBar.style.tsx
  client/src/components/SideBar/SideBar.tsx
  client/src/components/Withdrawal.style.ts
  client/src/components/Withdrawal.tsx
  client/src/pages/Main.tsx
  client/src/pages/MyPage.style.ts
  client/src/pages/MyPage.tsx
  client/src/pages/Test.style.ts
Labels: fe

#201 Feat/#200 refactor an dfix study
  server/src/main/java/com/yes27/member/dto/MemberDto.java
  server/src/main/java/com/yes27/study/controller/StudyController.java
  server/src/main/java/com/yes27/study/dto/StudyDto.java
  server/src/main/java/com/yes27/study/mapper/StudyMapper.java
  server/src/main/java/com/yes27/study/service/StudyVoteService.java
  server/src/main/java/com/yes27/study_comment/controller/StudyCommentController.java
Labels: be, BareMinimum

#206 fix : PostscriptComment 변수 수정 #205
  server/src/main/java/com/yes27/postscripcomment/controller/PostscriptCommentController.java
  server/src/main/java/com/yes27/postscripcomment/dto/PostscriptCommentDto.java
  server/src/main/java/com/yes27/postscripcomment/entity/PostscriptComment.java
  server/src/main/java/com/yes27/postscripcomment/mapper/PostscriptCommentMapper.java
  server/src/main/java/com/yes27/postscripcomment/service/PostscriptCommentService.java
  server/src/main/java/com/yes27/postscript/controller/PostscriptController.java
Labels: be, BareMinimum

#190 client-sanghyun: Feat/#132 user api
  client/package-lock.json
  client/package.json
  client/src/atoms/index.tsx
  client/src/components/Button/LoginButton.tsx
  client/src/components/Header/MainHeader.tsx
  client/src/components/Header/Nickname.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/hooks/index.js
  client/src/pages/Login.style.ts
  client/src/pages/Login.tsx
  client/src/pages/SignUp.style.tsx
  client/src/pages/SignUp.tsx
  client/src/utils/api/userAPI.ts
  client/src/utils/index.js
Labels: fe, BareMinimum

#209 client-sanghyun:Feat/#208 client logout
  client/src/components/Button/Logout.tsx
  client/src/components/Header/PageHeader.tsx
Labels: fe, BareMinimum
