Repository codestates-seb/seb40_main_027, pull requests merged in 2022-12, with the labels that each got.

#216 fix : postscriptLike-improvement vote 유저 확인 추가 및 변수 조정 #56
  server/src/main/java/com/yes27/postscript/controller/PostscriptVoteController.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptDto.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptVoteResponseDto.java
  server/src/main/java/com/yes27/postscript/entity/Postscript.java
  server/src/main/java/com/yes27/postscript/entity/PostscriptVote.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptMapper.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptVoteMapper.java
  server/src/main/java/com/yes27/postscript/repository/PostscriptVoteRepository.java
  server/src/main/java/com/yes27/postscript/service/PostscriptService.java
  server/src/main/java/com/yes27/postscript/service/PostscriptVoteService.java
Labels: be, BareMinimum

#212 client-jongwon: 게시글 CRUD 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/constant/TAG.ts
  client/src/components/Button/MoreButton.tsx
  client/src/components/Button/OtherButton.tsx
  client/src/components/Button/TagButton.tsx
  client/src/components/Button/WriteButton.tsx
  client/src/components/Forum/ForumArticle.tsx
  client/src/components/Forum/ForumArticles.style.ts
  client/src/components/Forum/ForumArticles.tsx
  client/src/components/Forum/ForumCard.tsx
  client/src/components/Forum/ForumCards.tsx
  client/src/components/Forum/ForumContentHeader.style.ts
  client/src/components/Forum/ForumContentHeader.tsx
  client/src/components/Forum/ForumDetail.style.ts
  client/src/components/Forum/ForumDetail.tsx
  client/src/components/Forum/ForumWrite.style.ts
  client/src/components/Forum/ForumWrite.tsx
  client/src/components/Forum/ForumWrittenInfo.tsx
  client/src/pages/Forum.tsx
  client/src/utils/api/forumAPI.ts
Labels: BareMinimum

#229 client-jongwon: 게시판 crud 외 기능 구현
  client/src/components/Button/FilterButton.style.ts
  client/src/components/Button/FilterButton.tsx
  client/src/components/Forum/ForumArticles.tsx
  client/src/components/Forum/ForumCards.tsx
  client/src/components/Forum/ForumContentHeader.tsx
  client/src/components/Forum/ForumDetail.style.ts
  client/src/components/Forum/ForumDetail.tsx
  client/src/pages/BootCamp.tsx
  client/src/utils/api/forumAPI.ts
Labels: fe, BareMinimum

#226 client-yoonkyoung: comment
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/image/LoadMapBanner.png
  client/src/assets/image/LoadMapMobile.png
  client/src/atoms/index.tsx
  client/src/components/Answer/AnswerContainer.tsx
  client/src/components/Answer/AnswerListView.style.ts
  client/src/components/Answer/AnswerListView.tsx
  client/src/components/Answer/ForumAnswer.style.ts
  client/src/components/Answer/ForumArticlesAnswer.tsx
  client/src/components/Answer/MentoringAnswer.tsx
  client/src/components/Answer/MentoringAnswerList.tsx
  client/src/components/Answer/StudyAnswer.tsx
  client/src/components/Answer/StudyAnswerList.tsx
  client/src/components/Forum/ForumDetail.tsx
  client/src/components/Header/Nickname.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/components/MyPageContent/MyPageList.tsx
  client/src/components/MyPageContent/MyPageLists.style.ts
  client/src/components/MyPageContent/MyPageLists.tsx
  client/src/components/MyPageContent/MyPageTable.tsx
  client/src/components/MyPageContent/UserProfile.style.ts
  client/src/components/MyPageContent/UserProfile.tsx
  client/src/components/Pagination/MyPagePagination.tsx
  client/src/components/SideBar/SideBar.tsx
  client/src/pages/LoadMap.tsx
  client/src/pages/Main.tsx
  client/src/utils/api/answerAPI.ts
Labels: fe

#241 client-jongwon: 필터버튼 로직 수정
  client/package-lock.json
  client/src/components/Button/FilterButton.tsx
  client/src/components/Forum/ForumContentHeader.tsx
  client/src/pages/BootCamp.tsx
Labels: bug, fe

#242 refactor : 중복 삭제 및 주석 및 가독성 증가 기능 개선 #239
  server/src/main/java/com/yes27/postscripcomment/controller/PostscriptCommentController.java
  server/src/main/java/com/yes27/postscripcomment/dto/PostscriptCommentDto.java
  server/src/main/java/com/yes27/postscripcomment/mapper/PostscriptCommentMapper.java
  server/src/main/java/com/yes27/postscripcomment/service/PostscriptCommentService.java
  server/src/main/java/com/yes27/postscript/controller/PostscriptController.java
  server/src/main/java/com/yes27/postscript/controller/PostscriptVoteController.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptDto.java
  server/src/main/java/com/yes27/postscript/dto/PostscriptVoteResponseDto.java
  server/src/main/java/com/yes27/postscript/dto/TagDto.java
  server/src/main/java/com/yes27/postscript/dto/TagResponseDto.java
  server/src/main/java/com/yes27/postscript/entity/Postscript.java
  server/src/main/java/com/yes27/postscript/entity/PostscriptView.java
  server/src/main/java/com/yes27/postscript/entity/Tag.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptMapper.java
  server/src/main/java/com/yes27/postscript/mapper/PostscriptVoteMapper.java
  server/src/main/java/com/yes27/postscript/repository/PostscriptRepository.java
  server/src/main/java/com/yes27/postscript/repository/PostscriptVoteRepository.java
  server/src/main/java/com/yes27/postscript/repository/TagRepository.java
  server/src/main/java/com/yes27/postscript/service/PostscriptService.java
  server/src/main/java/com/yes27/postscript/service/PostscriptViewService.java
  server/src/main/java/com/yes27/postscript/service/PostscriptVoteService.java
  server/src/main/java/com/yes27/postscript/service/TagService.java
Labels: be, Advanced

#245 client-yoonkyoung: mypage list
  client/src/atoms/index.tsx
  client/src/components/Answer/StudyAnswer.tsx
  client/src/components/Forum/ForumArticles.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/components/MyPageContent/BootLikeButton.tsx
  client/src/components/MyPageContent/MyPageList.tsx
  client/src/components/MyPageContent/MyPageLists.tsx
  client/src/components/MyPageContent/MyPageTable.style.ts
  client/src/components/MyPageContent/MyPageTable.tsx
  client/src/components/MyPageContent/UserProfile.style.ts
  client/src/components/MyPageContent/UserProfile.tsx
  client/src/components/MyPageContent/Withdrawal.style.ts
  client/src/components/MyPageContent/Withdrawal.tsx
  client/src/components/Pagination/PagePagination.tsx
  client/src/components/TestForm/EndForm.style.ts
  client/src/components/TestForm/EndForm.tsx
  client/src/components/TestForm/StartForm.tsx
  client/src/components/TestForm/TypeForm.style.ts
  client/src/components/TestForm/TypeForm.tsx
  client/src/pages/Forum.style.ts
  client/src/pages/LoadMap.tsx
  client/src/utils/api/forumAPI.ts
Labels: fe

#251 client-jongwon: react quill로 작성한 본문 스타일 수정
  client/src/components/Answer/AnswerListView.style.ts
  client/src/components/Forum/ForumDetail.style.ts
  client/src/components/Forum/ForumDetail.tsx
  client/src/styles/QuillContentBody.style.ts
Labels: bug

#255 client-jongwon: 게시판 사이드 배너 기능 구현
  client/src/components/Forum/ForumSideBanners.style.ts
  client/src/components/Forum/ForumSideBanners.tsx
  client/src/pages/Forum.tsx
  client/src/utils/api/forumAPI.ts
Labels: fe, BareMinimum

#258 client-sanghyun: Feat/#250 auth routing
  client/src/App.tsx
  client/src/components/Button/Logout.tsx
  client/src/components/Route/AuthRoute.tsx
  client/src/components/Route/PrivateRoute.tsx
  client/src/pages/Login.tsx
  client/src/utils/api/userAPI.ts
Labels: fe, BareMinimum

#257 client-sanghyun: Feat/#175 client bootcamp
  client/src/App.tsx
  client/src/components/Forum/ForumCards.style.ts
  client/src/components/Forum/ForumCards.tsx
  client/src/components/Loading/Loading.tsx
  client/src/components/MyPageContent/MyPageTable.style.ts
  client/src/components/MyPageContent/MyPageTable.tsx
  client/src/components/Table/DetailTable.style.ts
  client/src/components/Table/DetailTable.tsx
  client/src/components/Table/Table.style.ts
  client/src/components/Table/Table.tsx
  client/src/hooks/useBootTable.tsx
  client/src/pages/BootCamp.style.ts
  client/src/pages/BootCamp.tsx
  client/src/pages/BootCampDetail.style.ts
  client/src/pages/BootCampDetail.tsx
  client/src/utils/api/forumAPI.ts
Labels: fe, BareMinimum

#262 client-jongwon: 수정, 삭제 권한에 따라 버튼 렌더링 여부 적용
  client/src/components/Answer/AnswerContainer.tsx
  client/src/components/Forum/ForumDetail.tsx
Labels: fe, BareMinimum

#259 client-yoonkyoung cssrefactor
  client/package-lock.json
  client/package.json
  client/public/favicon2.ico
  client/public/index.html
  client/src/assets/image/testImg1.png
  client/src/assets/image/testImg2.png
  client/src/assets/image/testImg3.png
  client/src/assets/image/testImg4.png
  client/src/assets/image/testImg5.png
  client/src/assets/image/testImg6.png
  client/src/assets/image/testImg7.png
  client/src/assets/image/testImg8.png
  client/src/assets/image/testImg9.png
  client/src/atoms/index.tsx
  client/src/components/Answer/AnswerListView.tsx
  client/src/components/Answer/MentoringAnswerList.tsx
  client/src/components/Answer/StudyAnswerList.tsx
  client/src/components/Button/Logout.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/MainHeader.tsx
  client/src/components/Header/Nickname.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/components/MyPageContent/BootLikeButton.tsx
  client/src/components/MyPageContent/MyPageSchedule.style.ts
  client/src/components/MyPageContent/MyPageTable.tsx
  client/src/components/MyPageContent/UserProfile.tsx
  client/src/components/MyPageContent/Withdrawal.tsx
  client/src/components/SideBar/SideBar.tsx
  client/src/components/Table/Table.style.ts
  client/src/components/TestForm/TypeForm.tsx
  client/src/pages/BootCamp.style.ts
  client/src/pages/Login.style.ts
  client/src/pages/SignUp.style.tsx
  client/src/pages/SignUp.tsx
  client/src/utils/api/forumAPI.ts
Labels: fe

#265 client-sanghyun: Feat/#264 bug token logout
  client/src/index.tsx
  client/src/pages/Login.tsx
  client/src/utils/api/userAPI.ts
Labels: bug, fe

#270 client-sanghyun: Feat/#266 refac boot page
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/App.tsx
  client/src/assets/image/LoadMapBanner.png
  client/src/assets/image/LoadMapMobile.png
  client/src/assets/image/RoadMapLeft.png
  client/src/assets/image/RoadMapRight.png
  client/src/assets/image/review.png
  client/src/assets/image/reviewmobile.png
  client/src/assets/image/scheduledetails.png
  client/src/assets/image/scheduledetailsmobile.png
  client/src/components/Banner/index.style.tsx
  client/src/components/Banner/index.tsx
  client/src/components/Header/PageHeader.tsx
  client/src/components/SideBar/SideBar.tsx
  client/src/components/Table/DetailTable.style.ts
  client/src/components/Table/DetailTable.tsx
  client/src/components/Table/Table.style.ts
  client/src/components/Table/Table.tsx
  client/src/pages/BootCamp.style.ts
  client/src/pages/BootCampDetail.tsx
  client/src/pages/Main.tsx
  client/src/pages/RoadMap.tsx
  client/src/pages/Test.style.ts
Labels: bug
